name: Docker Scout Scan

on:
  workflow_dispatch:

jobs:
  docker-scout:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t pygoat:latest .

      # Run Docker Scout vulnerability scan
      - name: Docker Scout scan
        env:
          DOCKER_SCOUT_ENABLED: "true"
        run: |
          docker scout quickview pygoat:latest --json > scout-report-quickview.json
          docker scout cves pygoat:latest --json > scout-report-cves.json

      # Optional: Upload Scout report as artifact
      - name: Upload Scout report
        uses: actions/upload-artifact@v4
        with:
          name: docker-scout-report
          path: scout-report-cves.json,scout-report-quickview.json
