name: Trivy Container Image Scan (Docker)

on:
  workflow_dispatch:
    inputs:
      severity:
        description: "Choose severity level:"
        required: true
        default: "CRITICAL,HIGH,MEDIUM"
        type: choice
        options:
          - CRITICAL
          - HIGH
          - MEDIUM
          - "CRITICAL,HIGH"
          - "MEDIUM,HIGH"
          - "CRITICAL,MEDIUM"
          - "CRITICAL,HIGH,MEDIUM"

jobs:
  trivy-image-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t pygoat:latest .
          docker images

      - name: Run Trivy Container Image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: pygoat:latest
          severity: ${{ inputs.severity }}
          format: "sarif"
          output: "trivy-image-scan.sarif"
          exit-code: "0"
        # env:
        #   TRIVY_SKIP_DB_UPDATE: true
        #   TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Download Trivy Scan Report Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan
          path: trivy-image-scan.sarif